package com.lynxspa.sdm.dictionaries.formats.swift.messages;


import com.lynxspa.sdm.installer.adapters.formats.fields.CAMessageTypeFieldsDictAdapter;


public enum CAMessageType568Field implements CAMessageTypeFieldsDictAdapter{

	FIELD1("1:APPID:","application","STRING",1,null,"message.info",0,0,"Application ID: F = FIN(financial application),A = GPA(general purpose application),L = GPA(for logins, and so on)",true),
	FIELD2("1:SRVID:","service","INTEGER",2,null,"message.info",0,0,"Service ID: 01 = FIN/GPA, 21 = ACK/NAK",true),
	FIELD3("1:TERM:","terminal","STRING",12,null,"message.info",0,0,"Logical terminal (LT) address.",true),
	FIELD4("1:SESSN:","session","INTEGER",4,null,"message.info",0,0,"Session number. It is generated by the user's computer and is padded with zeros.",true),
	FIELD5("1:SEQN:","sequence","INTEGER",6,null,"message.info",0,0,"Sequence number that is generated by the user's computer. It is padded with zeros.",true),
	FIELD6("2:IO:","input output","STRING",1,null,"message.info",0,0,"Input/Output indicator",true),
	FIELD7("2:MSGT:","message type","INTEGER",3,null,"message.info",0,0,"Message type",true),
	FIELD8("2:I:ADD:","receivers address","STRING",12,null,"message.info",0,0,"Receiver's address with X in position 9/ It is padded with Xs if no branch is required.",true),
	FIELD9("2:I:MSGP:","message priority","STRING",1,null,"message.info",0,0,"The message priority as follows: S = System, N = Normal, U = Urgent",true),
	FIELD10("2:I:DMF:","delivery monitoring","INTEGER",1,null,"message.info",0,0,"Delivery monitoring field is as follows: 1 = Non delivery warning (MT010), 2 = Delivery notification (MT011), 3 = Both valid = U",true),
	FIELD11("2:I:OBP:","obsolescence period","INTEGER",3,null,"message.info",0,0,"Obsolescence period. It specifies when a non-delivery notification is generated as follows:",true),
	FIELD12("2:O:MIR:TIME","input time respect sender","DATE",4,"HHmm","message.info",0,0,"Input time with respect to the sender",true),
	FIELD13("2:O:MIR:DATE","input date respect sender","DATE",6,"yyMMdd","message.info",0,0,"Input date with respect to the sender",true),
	FIELD14("2:O:MIR:ADD:","sender address","STRING",12,null,"message.info",0,0,"The Message Input Reference (MIR), including input date, with Sender's address",true),
	FIELD15("2:O:MIR:SESSN:","sender session","INTEGER",4,null,"message.info",0,0,"Sender session",true),
	FIELD16("2:O:MIR:SEQN:","sender sequence","INTEGER",6,null,"message.info",0,0,"Sender sequence",true),
	FIELD17("2:O:DATE:","output date respect receiver","DATE",6,"yyMMdd","message.info",0,0,"Output date with respect to Receiver",true),
	FIELD18("2:O:TIME:","output time respect receiver","DATE",4,"HHmm","message.info",0,0,"Output time with respect to Receiver",true),
	FIELD19("2:O:MSGP:","message priority","STRING",1,null,"message.info",0,0,"The message priority as follows: S = System, N = Normal, U = Urgent",true),
	FIELD20("3:113:","optional banking priority code","STRING",4,null,"message.user.info",0,0,"Optional banking priority code",true),
	FIELD21("3:108:","message user reference","STRING",0,null,"message.user.info",0,0,"Message User Reference",true),
	FIELD22("4:16R:GENL:20::CORP/","corporate action reference","STRING",0,null,null,0,0,"Reference assigned by the account servicer to unambiguously identify a corporate action event.",false),
	FIELD23("4:16R:GENL:20::SEME/","sender message reference","STRING",0,null,null,0,0,"Reference assigned by the Sender to unambiguously identify the message.",false),
	FIELD24("4:16R:GENL:23:","message function","STRING",0,null,null,0,0,"Message requesting the cancellation of a previously sent message.",true),
	FIELD25("4:16R:GENL:22::CAEV/","corporate action event indicator","STRING",0,null,null,0,0,"Specifies the type of corporate event.",false),
	FIELD26("4:16R:GENL:98::PREP/","preparation date","STRING",0,null,null,0,0,"Date at which message was prepared.",false),
	FIELD27("4:16R:GENL:16R:LINK:22::LINK/","linkage type indicator","STRING",0,null,null,0,0,"Specifies when the instruction is to be executed relative to a linked instruction.",false),
	FIELD28("4:16R:GENL:16R:LINK:13::LINK/","linked message","STRING",0,null,null,0,0,"Message type number / message identifier of the message referenced in the linkage sequence.",false),
	FIELD29("4:16R:GENL:16R:LINK:20::PREV/","previous message reference","STRING",0,null,null,0,0,"Message reference of the linked message which was previously sent.",false),
	FIELD30("4:16R:GENL:16R:LINK:20::RELA/","related message reference","STRING",0,null,null,0,0,"Message reference of the linked message which was previously received.",false),
	FIELD31("4:16R:USECU:95::ACOW/","account owner","STRING",0,null,null,0,0,"Party that owns the account.",false),
	FIELD32("4:16R:USECU:97::SAFE/","safekeeping account","STRING",0,null,null,0,0,"Account where financial instruments are maintained.",false),
	FIELD33("4:16R:USECU:94::SAFE/","place of safekeeping","STRING",0,null,null,0,0,"Location where the financial instruments are/will be safekept.",false),
	FIELD34("4:16R:USECU:35:","identification of security","STRING",0,null,null,0,0,"Identifies the financial instrument.",false),
	FIELD35("4:16R:USECU:16R:FIA:94::PLIS/","place of listing","STRING",0,null,null,0,0,"Place where the referenced financial instrument is listed.",false),
	FIELD36("4:16R:USECU:16R:FIA:22::MICO/","method of interest computation indicator","STRING",0,null,null,0,0,"Specifies the computation method of (accrued) interest of the financial instrument.",false),
	FIELD37("4:16R:USECU:16R:FIA:12::CLAS/","classification type","STRING",0,null,null,0,0,"Classification type of the financial instrument, e.g., ISO Classification of Financial instrument (CFI).",false),
	FIELD38("4:16R:USECU:16R:FIA:11::DENO/","currency of denomination","STRING",0,null,null,0,0,"Currency in which a financial instrument is currently denominated",false),
	FIELD39("4:16R:USECU:16R:FIA:98::CALD/","call date","STRING",0,null,null,0,0,"Date on which a financial instrument is called away/redeemed before its scheduled maturity.",false),
	FIELD40("4:16R:USECU:16R:FIA:98::CONV/","conversion date","STRING",0,null,null,0,0,"Deadline by which a convertible security must be converted, according to the terms of the issue.",false),
	FIELD41("4:16R:USECU:16R:FIA:98::COUP/","coupon date","STRING",0,null,null,0,0,"Next payment date of an interest bearing financial instrument.",false),
	FIELD42("4:16R:USECU:16R:FIA:98::DDTE/","dated date","STRING",0,null,null,0,0,"Date on which an interest bearing financial instrument begins to accrue interest.",false),
	FIELD43("4:16R:USECU:16R:FIA:98::EXPI/","expiry date","STRING",0,null,null,0,0,"Date on which an order expires or at which a privilege or offer terminates.",false),
	FIELD44("4:16R:USECU:16R:FIA:98::FRNR/","floating rate note reset date","STRING",0,null,null,0,0,"Date on which the interest rate of an interest bearing financial instrument will be/was calculated and reset, according to the t",false),
	FIELD45("4:16R:USECU:16R:FIA:98::ISSU/","issue date","STRING",0,null,null,0,0,"Date on which the financial instrument is issued.",false),
	FIELD46("4:16R:USECU:16R:FIA:98::MATU/","maturity date","STRING",0,null,null,0,0,"Date on which a financial instrument becomes due and assets are to be repaid.",false),
	FIELD47("4:16R:USECU:16R:FIA:98::PUTT/","put date","STRING",0,null,null,0,0,"Date on which a holder of a financial instrument has the right to request redemption of the principal amount prior to its schedu",false),
	FIELD48("4:16R:USECU:16R:FIA:92::INTR/","interest rate","STRING",0,null,null,0,0,"Annual rate of a financial instrument.",false),
	FIELD49("4:16R:USECU:16R:FIA:92::NWFC/","next factor","STRING",0,null,null,0,0,"Factor used to calculate the value of the outstanding principal of the financial instrument (for factored securities) that will ",false),
	FIELD50("4:16R:USECU:16R:FIA:92::NXRT/","next interest rate","STRING",0,null,null,0,0,"Interest rate applicable to the next interest payment period in relation to variable rate instruments.",false),
	FIELD51("4:16R:USECU:16R:FIA:92::PRFC/","previous factor","STRING",0,null,null,0,0,"Factor used to calculate the value of the outstanding principal of the financial instrument (for factored securities) until the ",false),
	FIELD52("4:16R:USECU:16R:FIA:36::MIEX/","minimum exercisable quantity","STRING",0,null,null,0,0,"Minimum quantity of financial instrument or lot of rights/warrants that must be exercised.",false),
	FIELD53("4:16R:USECU:16R:FIA:36::MILT/","minimum exercisable multiple quantity","STRING",0,null,null,0,0,"Minimum multiple quantity of financial instrument or lot of rights/warrants that must be exercised.",false),
	FIELD54("4:16R:USECU:16R:FIA:36::MINO/","minimum nominal quantity minimum nominal value quantity","STRING",0,null,null,0,0,"Minimum nominal quantity of financial instrument that must be purchased/sold.",false),
	FIELD55("4:16R:USECU:16R:FIA:36::SIZE/","contract size quantity ","STRING",0,null,null,0,0,"Ratio or multiplying factor used to convert one contract into a financial instrument quantity.",false),
	FIELD56("4:16R:USECU:93::BLOK/","blocked balance","STRING",0,null,null,0,0,"Balance of financial instruments that are blocked.",false),
	FIELD57("4:16R:USECU:93::BORR/","borrowed balance","STRING",0,null,null,0,0,"Balance of financial instruments that have been borrowed from another party",false),
	FIELD58("4:16R:USECU:93::COLI/","collateral in balance","STRING",0,null,null,0,0,"Balance of securities that belong to a third party and that are held for the purpose of collateralisation.",false),
	FIELD59("4:16R:USECU:93::COLO/","collateral out balance","STRING",0,null,null,0,0,"Balance of securities that belong to the safekeeping account indicated within this message, and are deposited with a third party",false),
	FIELD60("4:16R:USECU:93::CONB/","confirmed balance","STRING",0,null,null,0,0,"Balance of securities that was confirmed.",false),
	FIELD61("4:16R:USECU:93::ELIG/","total eligible for corporate action balance","STRING",0,null,null,0,0,"Total balance of securities eligible for this corporate action event. The entitlement calculation is based on this balance",false),
	FIELD62("4:16R:USECU:93::LOAN/","on loan balance ","STRING",0,null,null,0,0,"Balance of financial instruments that have been loaned to a third party",false),
	FIELD63("4:16R:USECU:93::NOMI/","registered balance","STRING",0,null,null,0,0,"Balance of financial instruments that are registered (in the name of a nominee name or of the beneficial owner).",false),
	FIELD64("4:16R:USECU:93::PEND/","pending delivery balance","STRING",0,null,null,0,0,"Balance of financial instruments that are pending delivery.",false),
	FIELD65("4:16R:USECU:93::PENR/","pending receipt balance","STRING",0,null,null,0,0,"Balance of financial instruments that are pending receipt.",false),
	FIELD66("4:16R:USECU:93::REGO/","out for registration balance","STRING",0,null,null,0,0,"Balance of financial instruments currently being processed by the institution responsible for registering the new beneficial own",false),
	FIELD67("4:16R:USECU:93::SETT/","settlement position balance","STRING",0,null,null,0,0,"Balance of securities representing only settled transactions; pending transactions not included.",true),
	FIELD68("4:16R:USECU:93::SPOS/","street position balance","STRING",0,null,null,0,0,"Balance of financial instruments that remain registered in the name of the prior beneficial owner.",false),
	FIELD69("4:16R:USECU:93::TRAD/","trade date position balance","STRING",0,null,null,0,0,"Balance of securities based on trade date, e.g., includes all pending transactions in addition to the balance of settled transac",false),
	FIELD70("4:16R:USECU:93::TRAN/","in transhipment balance","STRING",0,null,null,0,0,"Balance of physical securities that are in the process of being transferred from one depository/agent to another.",false),
	FIELD71("4:16R:ADDINFO:70::ADTX/","additional text","STRING",0,null,null,0,0,"Provides additional information or specifies in more detail the content of a message. This field may only be used when the infor",false),
	FIELD72("4:16R:ADDINFO:70::COMP/","information to be complied with","STRING",0,null,null,0,0,"Provides information conditions to the account owner that are to be complied with, e.g., not open to US/Canadian residents, QIB ",false),
	FIELD73("4:16R:ADDINFO:70::DISC/","disclaimer","STRING",0,null,null,0,0,"Provides a disclaimer relative to the information provided in the message. It may be ignored for automated processing.",false),
	FIELD74("4:16R:ADDINFO:70::INCO/","information conditions","STRING",0,null,null,0,0,"Provides conditional information related to the event, e.g., an offer is subject to 50% acceptance, the offeror allows the secur",false),
	FIELD75("4:16R:ADDINFO:70::PACO/","party narrative","STRING",0,null,null,0,0,"Provides additional information regarding the party, e.g., the contact unit or person responsible for the transaction identified",false),
	FIELD76("4:16R:ADDINFO:70::REGI/","registration details","STRING",0,null,null,0,0,"Provides information required for the registration.",false),
	FIELD77("4:16R:ADDINFO:70::TAXE/","taxation conditions","STRING",0,null,null,0,0,"Provides taxation conditions that cannot be included within the structured fields of this message and has not been mentioned in ",false),
	FIELD78("4:16R:ADDINFO:70::WEBB/","web site address","STRING",0,null,null,0,0,"Provides the web address published for the event, i.e. the address for the Universal Resource Locator (URL), e.g., used over the",false),
	FIELD79("4:16R:ADDINFO:95::MEOR/","originator of message","STRING",0,null,null,0,0,"Party that originated the message, if other than the Sender",false),
	FIELD80("4:16R:ADDINFO:95::MERE/","recipient of message","STRING",0,null,null,0,0,"Party that is the final destination of the message, if other than the Receiver.",false),
	FIELD81("5:MAC:","message authentication code","STRING",0,null,"message.trailer.info",0,0,"Message authentication code",true),
	FIELD82("5:CHK:","checksum","STRING",0,null,"message.trailer.info",0,0,"Checksum",true),
	FIELD83("5:PDE:","possible duplicates emission","STRING",0,null,"message.trailer.info",0,0,"Possible duplicates emission",true),
	FIELD84("5:DLM:","urgent","STRING",0,null,"message.trailer.info",0,0,"urgent",true),
	FIELD85("S:SAC:","sac","STRING",0,null,"message.trailer.info",0,0,"sac",true),
	FIELD86("S:COP:","cop","STRING",0,null,"message.trailer.info",0,0,"cop",true);	


	private String path=null; 
	private String fieldName=null; 
	private int fieldLength=0; 
	private String fieldType=null; 
	private String fieldFormat=null; 
	private String displayGroup=null; 
	private int displayRow=0; 
	private int displayColumn=0; 
	private String description=null;
	private boolean hidden=false;

	
	CAMessageType568Field(String _path,String _fieldName,String _fieldType,int _fieldLength,String _fieldFormat,String _displayGroup,int _displayRow,int _displayColumn,String _description,boolean _hidden){
		this.path=_path;
		this.fieldName=_fieldName;
		this.fieldLength=_fieldLength;
		this.fieldType=_fieldType;
		this.fieldFormat=_fieldFormat;
		this.displayGroup=_displayGroup;
		this.displayRow=_displayRow;
		this.displayColumn=_displayColumn;
		this.description=_description;
		this.hidden=_hidden;
	}

	
	public String getPath() {
		return path;
	}
	public String getFieldName() {
		return fieldName;
	}
	public int getFieldLength() {
		return fieldLength;
	}
	public String getFieldType() {
		return fieldType;
	}
	public String getFieldFormat() {
		return fieldFormat;
	}
	public String getDisplayGroup() {
		return displayGroup;
	}
	public int getDisplayRow() {
		return displayRow;
	}
	public int getDisplayColumn() {
		return displayColumn;
	}
	public String getDescription() {
		return description;
	}
	public boolean getHidden() {
		return hidden;
	}
}
