package com.lynxspa.entities.jobs.beans;

// Generated 31-mar-2014 12:33:54 by Hibernate Tools 3.2.0.b9

import com.lynxspa.entities.UpdateAuditor;

/**
 * SDMJob generated by hbm2java
 */
public class SDMJobBean {

	private long id;
	private String file;
	private int version;
	private int numSuccess;
	private int numRecords;
	private SDMJobTypeBean jobType;
	private int numFailed;
	private UpdateAuditor auditor;

	public SDMJobBean() {
	}

	public SDMJobBean(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

	public SDMJobBean(String file, int numSuccess, int numRecords,
			SDMJobTypeBean jobType, int numFailed, UpdateAuditor auditor) {
		this.file = file;
		this.numSuccess = numSuccess;
		this.numRecords = numRecords;
		this.jobType = jobType;
		this.numFailed = numFailed;
		this.auditor = auditor;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getNumSuccess() {
		return this.numSuccess;
	}

	public void setNumSuccess(int numSuccess) {
		this.numSuccess = numSuccess;
	}

	public int getNumRecords() {
		return this.numRecords;
	}

	public void setNumRecords(int numRecords) {
		this.numRecords = numRecords;
	}

	public SDMJobTypeBean getJobType() {
		return this.jobType;
	}

	public void setJobType(SDMJobTypeBean jobType) {
		this.jobType = jobType;
	}

	public int getNumFailed() {
		return this.numFailed;
	}

	public void setNumFailed(int numFailed) {
		this.numFailed = numFailed;
	}

	public UpdateAuditor getAuditor() {
		return this.auditor;
	}

	public void setAuditor(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

}
