package com.lynxspa.entities.jobs.beans;

// Generated 31-mar-2014 12:33:54 by Hibernate Tools 3.2.0.b9

import com.lynxspa.entities.UpdateAuditor;

/**
 * SDMJobType generated by hbm2java
 */
public class SDMJobTypeBean {

	private long id;
	private String name;
	private String description;
	private int version;
	private UpdateAuditor auditor;

	public SDMJobTypeBean() {
	}

	public SDMJobTypeBean(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

	public SDMJobTypeBean(String name, String description, UpdateAuditor auditor) {
		this.name = name;
		this.description = description;
		this.auditor = auditor;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public UpdateAuditor getAuditor() {
		return this.auditor;
	}

	public void setAuditor(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

}
