package com.lynxspa.entities.jobs.beans;

// Generated 31-mar-2014 12:33:54 by Hibernate Tools 3.2.0.b9

import com.lynxspa.entities.UpdateAuditor;

/**
 * SDMJobField generated by hbm2java
 */
public class SDMJobFieldBean {

	private long id;
	private String name;
	private String fieldType;
	private String mask;
	private String description;
	private int version;
	private SDMJobTypeBean jobType;
	private UpdateAuditor auditor;
	private String longDescription;

	public SDMJobFieldBean() {
	}

	public SDMJobFieldBean(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

	public SDMJobFieldBean(String name, String fieldType, String mask,
			String description, SDMJobTypeBean jobType, UpdateAuditor auditor,
			String longDescription) {
		this.name = name;
		this.fieldType = fieldType;
		this.mask = mask;
		this.description = description;
		this.jobType = jobType;
		this.auditor = auditor;
		this.longDescription = longDescription;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

	public String getMask() {
		return this.mask;
	}

	public void setMask(String mask) {
		this.mask = mask;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public SDMJobTypeBean getJobType() {
		return this.jobType;
	}

	public void setJobType(SDMJobTypeBean jobType) {
		this.jobType = jobType;
	}

	public UpdateAuditor getAuditor() {
		return this.auditor;
	}

	public void setAuditor(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

}
