package com.lynxspa.entities.jobs.beans;

// Generated 31-mar-2014 12:33:54 by Hibernate Tools 3.2.0.b9

import com.lynxspa.entities.UpdateAuditor;

/**
 * SDMRow generated by hbm2java
 */
public class SDMRowBean {

	private long id;
	private String value;
	private int version;
	private SDMStatusBean status;
	private SDMJobBean job;
	private UpdateAuditor auditor;

	public SDMRowBean() {
	}

	public SDMRowBean(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

	public SDMRowBean(String value, SDMStatusBean status, SDMJobBean job,
			UpdateAuditor auditor) {
		this.value = value;
		this.status = status;
		this.job = job;
		this.auditor = auditor;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public SDMStatusBean getStatus() {
		return this.status;
	}

	public void setStatus(SDMStatusBean status) {
		this.status = status;
	}

	public SDMJobBean getJob() {
		return this.job;
	}

	public void setJob(SDMJobBean job) {
		this.job = job;
	}

	public UpdateAuditor getAuditor() {
		return this.auditor;
	}

	public void setAuditor(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

}
