package com.lynxspa.entities.jobs.beans;

// Generated 31-mar-2014 12:33:54 by Hibernate Tools 3.2.0.b9

/**
 * SDMStatus generated by hbm2java
 */
public class SDMStatusBean {

	private long id;
	private String name;
	private String description;
	private String code;

	public SDMStatusBean() {
	}

	public SDMStatusBean(String name, String description, String code) {
		this.name = name;
		this.description = description;
		this.code = code;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
