package com.lynxspa.entities.jobs.beans;

// Generated 31-mar-2014 12:33:54 by Hibernate Tools 3.2.0.b9

import com.lynxspa.entities.UpdateAuditor;

/**
 * SDMValue generated by hbm2java
 */
public class SDMValueBean {

	private long id;
	private String value;
	private int version;
	private SDMRowBean row;
	private SDMJobFieldBean jobField;
	private UpdateAuditor auditor;

	public SDMValueBean() {
	}

	public SDMValueBean(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

	public SDMValueBean(String value, SDMRowBean row, SDMJobFieldBean jobField,
			UpdateAuditor auditor) {
		this.value = value;
		this.row = row;
		this.jobField = jobField;
		this.auditor = auditor;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public SDMRowBean getRow() {
		return this.row;
	}

	public void setRow(SDMRowBean row) {
		this.row = row;
	}

	public SDMJobFieldBean getJobField() {
		return this.jobField;
	}

	public void setJobField(SDMJobFieldBean jobField) {
		this.jobField = jobField;
	}

	public UpdateAuditor getAuditor() {
		return this.auditor;
	}

	public void setAuditor(UpdateAuditor auditor) {
		this.auditor = auditor;
	}

}
